-- phpMyAdmin SQL Dump
-- version 5.2.0
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Dec 05, 2022 at 08:28 AM
-- Server version: 10.4.25-MariaDB
-- PHP Version: 8.1.10

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `music`
--

-- --------------------------------------------------------

--
-- Table structure for table `accounts`
--

CREATE TABLE `accounts` (
  `email` varchar(255) NOT NULL,
  `user_type` varchar(255) NOT NULL DEFAULT 'USER',
  `password` varchar(255) NOT NULL,
  `name` varchar(255) NOT NULL,
  `flag` date DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `accounts`
--

INSERT INTO `accounts` (`email`, `user_type`, `password`, `name`, `flag`) VALUES
('admin@gmail.com', 'admin', 'e10adc3949ba59abbe56e057f20f883e', 'admin page', NULL),
('nguyentrungnghiacmp5123@gmail.com', 'user', 'e10adc3949ba59abbe56e057f20f883e', 'Nguyên Trung Nghĩa', '0000-00-00'),
('phuctran12421@gmail.com', 'user', '202cb962ac59075b964b07152d234b70', 'Tran Thanh Phuc', '0000-00-00');

-- --------------------------------------------------------

--
-- Table structure for table `play`
--

CREATE TABLE `play` (
  `number` int(11) NOT NULL,
  `id` int(11) NOT NULL,
  `email` varchar(255) NOT NULL,
  `likes` tinyint(1) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- --------------------------------------------------------

--
-- Table structure for table `songs`
--

CREATE TABLE `songs` (
  `id` int(11) NOT NULL,
  `name` varchar(255) NOT NULL,
  `singer` varchar(255) NOT NULL,
  `music` varchar(255) NOT NULL,
  `cover` varchar(255) NOT NULL,
  `lyrics` text NOT NULL,
  `tag` varchar(255) NOT NULL DEFAULT 'Nhạc, NCM',
  `view` int(255) NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `songs`
--

INSERT INTO `songs` (`id`, `name`, `singer`, `music`, `cover`, `lyrics`, `tag`, `view`) VALUES
(1, '1 Phút', 'Andiez', '637af250a829c.mp3', '637af250a829e.jpg', 'Đã bao lâu lòng này anh chẳng nói\nNói với em ngàn lời anh cất giữ trong tim\nLần này đến lần khác đôi môi cứ lãng phí chẳng nói gì\nChỉ biết cạnh em dù cho em chẳng để ý\nVà rồi em đã có người em yêu\nMỉm cười cho qua hết đi\nPhải chăng là do người đến sau yêu em thật nhiều\nNói thay anh những lời anh mong ước\nVà chúc cho em thật vui mặc anh bên lề của hạnh phúc\nMột phút giây ta đã qua anh sẽ giữ như thước phim\nĐể khi nhớ em anh xem và ước rằng thực tế sẽ như vậy\nỞ nơi đó thời gian như ngừng trôi hỡi em\nMột phút đứng trước mặt em một phút là xa lời chưa nói\nMột phút mạnh mẽ từ anh ta vẫn sẽ chung lối đi\nAnh chẳng thể nào quay lại để bây giờ chẳng nói giá như\nGiá như em hiểu rằng giá như em một lần nhìn được từ ánh mắt anh\nVà giờ em đã có người em yêu\nMỉm cười cho qua hết đi\nPhải chăng là do người đến sau yêu em thật nhiều\nNói thay anh những lời anh mong ước\nVà chúc cho em thật vui mặc anh bên lề của hạnh phúc\nMột phút giây ta đã qua anh sẽ giữ như thước phim\nĐể khi nhớ em anh xem và ước rằng thực tế sẽ như vậy\nỞ nơi đó thời gian như ngừng trôi hỡi em\nMột phút đứng trước mặt em một phút là xa lời chưa nói\nMột phút mạnh mẽ từ anh ta vẫn sẽ chung lối đi\nAnh chẳng thể nào quay lại để bây giờ chẳng nói giá như\nGiá như em hiểu rằng giá như anh một lần nhìn được\nVì trái tim anh cần em vì với anh em là duy nhất\nThế nhưng bây giờ đây chẳng thể đến được với nhau\nAnh đã sai thật rồi anh sai thật rồi\nVì cứ mãi giữ lời yêu em trong trái tim\nHuh oh\nMột phút đứng trước mặt em một phút là xa lời chưa nói\nMột phút mạnh mẽ từ anh ta vẫn sẽ chung lối đi\nAnh anh chẳng thể nào quay lại (anh chẳng thể quay trở về)\nĐể bây giờ chẳng nói giá như (chẳng nói giá như)\nGiá như em hiểu rằng giá như em một lần nhìn được từ ánh mắt anh', '1 Phút , Andiez , Indie , Nhạc Trẻ', 0),
(2, '11h11', 'Thái Đinh', '637af28504fbf.mp3', '637af28504fc4.jpg', 'Màn đêm xuống\nTừng hồi chuông\nNgập ngừng buông\nMình anh lặng giữa những cách xa\nEm à , mỗi giây , vụt qua…\nEm có còn … nhớ thương anh thật nhiều\n\nTừng hồi ức , còn thao thức\nThầm hình dung , ở phương trời đó chắc em đang , ngắm nhìn , đắm chìm vào những giấc mơ\nEm ơi , lòng này dõi theo em.\n\nChorus:\n\n11 giờ 11 phút là lúc ai đang lặng lẽ gửi trao nhớ thương.\nThật lòng anh vẫn luôn tin rằng , khoảnh khắc ấy ta gần/cần nhau.\n\n11 giờ 11 phút , liệu có ai đang lặng lẽ gửi trao nhớ thương?\nChẳng hay trong phút giây thoáng qua , người có vấn vương về anh.\n\n\nCho anh ngắm nhìn , lại đắm chìm , vào những chơi vơi vụn vỡ.\nTừng phút trôi qua vấn vương lại gì\nNhư là lúc đôi ta nhớ thương ai khi\nBao lời ngọt ngào phút chốc cuốn theo mây trời cùng những ước mong.\nLiệu nơi em có nghe được không?\n\nChorus:\n\n11 giờ 11 phút là lúc ai đang lặng lẽ gửi trao nhớ thương.\nThật lòng anh vẫn luôn tin rằng , khoảnh khắc ấy ta gần/cần nhau.\n\n11 giờ 11 phút , liệu có ai đang lặng lẽ gửi trao nhớ thương?\nChẳng hay trong phút giây thoáng qua , người có vấn vương về anh.\n\n\nRap:\nVà nếu một ngày kim giờ kim phút từng chút mang ta về nơi\nAnh ngồi đợi em bên hiên nhà cũ, để khẽ lau đi từng giọt lệ rơi\nĐể anh ôm em thật chặt, nói bao lời dù vẫn biết muộn màng\nĐể ta một lần đối mặt với những niềm nhớ mà lòng mình vẫn luôn mang\nVì anh không biết liệu em còn nhớ, nhớ ngày ta còn nhau\nVì anh không biết làm sao hàn gắn khi tim này vẫn còn đau\nVì anh không biết ta chờ đợi gì, ở đằng sau tan vỡ\nKhi trên con đường dang dở ta đã cùng nhau bỏ lại những điều đang mơ', '11h11 , Thái Đinh , Indie , Nhạc trẻ', 0),
(3, 'Bảy bước tới mùa hè', 'Đào Líuloo', '637af305c1214.mp3', '637af305c1216.jpg', 'Biết bao giờ cho tới mùa hè\nTrong sân trường tràn tiếng ve\nNắng tô vàng đôi cánh nhỏ xinh\nBên hiên nhà em lắng nghe\nTiếng chim hót líu lo\nTiếng đùa vui khắp nơi\nCánh đồng thơm hương lúa\nAi tô một màu vàng\nBiết bao giờ cho tới ngày xưa\nEm vẫn còn là bé thơ\nMá em hồng núng nính nhỏ xinh\nBên ông bà em rất thương\nBiết vui múa hát ca\nBiết nhảy dây bắn bi\nQuên sầu quên ai oán\nKhông yêu chẳng hận thù\nAi kia vội kết mây vội kết trời\nBỏ quên tháng năm vội vã trôi\nThương thân phận trách than trời lỡ làng\nMình em với em biết bao giờ\nAi kia vội kết mây vội kết trời\nBỏ quên tháng năm vội vã trôi\nThương thân phận trách than trời lỡ làng\nMình em với em biết bao giờ\nChiều nào nấu cơm\nChiều nào bế em\nMẹ về với hai đồng bánh thơm\nChiều nào lớn lên\nNgồi khóc bên hiên nhà\nChiều nào ước ao biết bao giờ\nBiết bao giờ cho tới mùa hè\nMây trên trời xanh rất xanh\nVẫn hiên nhà em bé cỏn con\nƯớc đâu cần chi lớn lên\nBiết bao giờ', 'Bảy bước tới mùa hè , Đào Líuloo, Indie , Nhạc trẻ', 0),
(4, 'Bụi hoa giấy', 'Trang', '637af367151dc.mp3', '637af367151df.jpg', 'Bụi hoa giấy hiên nhà lắng nghe\nTiếng mưa ru dịu dàng\nMùa hè sắp quay về với tôi\nTrong giấc mơ chỉ toàn người khóc\nNgười vui\nNgười điên\nTrên áng mây cao là hoàng hôn\nThổn thức tim tôi\nNhững ngày qua tôi ngồi lặng thinh\nCùng mấy cuốn sách dở dang chưa đọc hết\nNhững kí ức tôi ngỡ đã qua\nMà đứng giữa đám đông vẫn thấy mình cô đơn\nCon đường về đã đi cả ngàn lần\nTrở nên lạ lẫm không sao quen thuộc\nÔ kìa, bóng đèn đường vẫn lửng lơ chờ tôi\nChờ tôi\nBụi hoa giấy hiên nhà lắng nghe\nTiếng mưa ru dịu dàng\nMùa hè sắp quay về với tôi\nTrong giấc mơ chỉ toàn người khóc\nNgười vui\nNgười điên\nTrên áng mây cao là hoàng hôn\nThổn thức tim tôi\nVẫn một góc phố đông chiều mưa\nTôi nhìn quanh chỉ thấy xe cộ ngang chéo\nKhông đợi nhau không trông chờ nhau\nKhông tìm nhau như trong những bài hát\nƯớc gì tình yêu chỉ như làn sương\nMong manh tan theo vui đùa trong phút chốc\nVì ta còn trăm ngàn lo nghĩ vấn vương\nSao ngồi đây lo nghĩ một con người\nTa-đa-đa-ta-đa-đa-ta\nTa-đa-ta-đa-ta\nTa-đa-đa-ta-đa-đa-ta\nTa-đa-đa-ta-đa-đa-ta\nTa-đa-ta-đa-ta\nTa-đa-đa-ta-đa-đa-ta\nNgoài hè phố mưa rào vắng tanh\nTa đứng chung ô chờ đợi\nKìa tia nắng mai nào hé môi\nKhẽ hôn tôi thật nồng ấm\nLặng lẽ bên tôi\nNghe tiếng yêu anh thật nồng ấm\nThổn thức tim tôi\n', 'Bụi hoa giấy , Trang , Indie , Nhạc trẻ', 0),
(5, 'Chà đào', 'Thế Bảo, Gọi là Phúc', '637af3ca00c58.mp3', '637af3ca00c5d.jpg', 'Lê đôi chân lãng du bơ vơ\nMột sáng ngu ngơ tìm ai nghe chuyện đời ta\nThong dong cứ bước đi chẳng mang vội vã\nMây nương theo gió lây đung đưa\nVề quán thân quen từ những câu chuyện ngày xưa\nEm như tia nắng mai chợt len qua ô cửa\nXao xuyến tâm hồn anh\nYou knocked me out, u knocked me out\nBao giấc mơ ngọt ngào, một cốc \"chà đào\" vẫn như hôm nao\nĐể tim mình thôi xôn xao\nĐK\nVà có lẽ duyên trời định dần khiến em qua đây\nMắt môi em dịu dàng\nLàm sao anh có thể nén đi những cảm giác yêu lần đầu ấy\nEm đi qua thơm hương hoa nhài\nVà thấy sương ban mai vương trên tóc dài em bước\nCho hồn tôi miên man mỗi lúc khi nhìn người\nRap:\nNhư mọi khi cuối tuần anh diện áo sơ mi trắng đi uống \"chà đào\"\nEm thong thả cùng với váy đen túi Saint Laurent bước từ ngoài vào\nNhìn một phát lòng muốn hoảng loạn câu gieo vào bass cũng trật nhịp luôn\nNói hơi lố chút xíu là cái ánh nhìn của em ôi sao ngọt ngào\\Nngọt hơn trà đào anh chưa kịp uống\nĐang rap hay mà beat chuyển tone anh vẫn đa tài nên vẫn rap được đấy thôi\nKhông có gì thay đổi anh vẫn cách xa em tận bốn, năm bước chân lận đó ấy ơi\nMà sao ngộ đồng ý là anh nhát gái nhưng sao lần này lại nhát kinh thế\nNhìn em uống olong tea milk anh cũng thấy đẹp một cách tinh tế\nUống trà đào để lấy can đảm tiến lại em chậm chậm từng chút\n\"Mình ngồi đây được không?\" Đến câu thứ hai chuyển giọng \"mình tên là Phúc\"\nHổng hiểu sao lần đầu gặp mặt mà mình nói nhiều mà như đã quen\nXin số phone, khoan add facebook chờ anh xóa đống friend request đã em\nCoda\nAnh chỉ mong ngày mai bình yên thấy em sau đôi bờ vai\nLà mỗi lúc khi bên người thật mọi ưu phiền xa mãi\nĐôi khi ta đang buồn đau bao suy tư đang chìm sâu\nCứ mang ra kể cùng nhau suốt đêm thâu...', 'Chà đào , Thế Bảo , Gọi là Phúc , Indie , Nhạc trẻ', 0),
(6, 'Chắc anh đang', 'Tiên Tiên, Trang', '637af414f3950.mp3', '637af414f3954.png', 'Chắc anh đang ngủ vùi đâu đó\nTrong làn nắng thu vơi đầy\nChắc anh đang lạc đường quanh co\nKhi mặt trời xuống\nChắc anh đang tìm niềm vui mới\nBên hình bóng ai xa lạ\nNhững phút giây lạnh lùng chơi vơi\nKhi em nơi đây một mình\nVà rồi em biết để làm gì\nMình chẳng thể cùng sẻ chia\nCó bao nhiêu khoảng cách\nEm mong được lấp đầy\nAnh ơi!\nMà anh biết không? (anh biết không?)\nNhớ thương chìm trong bão giông (trong bão giông)\nBỏ lại em\nVang lên câu ca cho ngàn người xem\nCó những nỗi đau khi yêu không mang tên này\n(Có những nỗi đau khi yêu không mang tên này)\nGiờ em biết sao cho vừa\n(Giờ em biết sao cho vừa)\nThật lòng rằng em rất nhớ\nAnh của ngày xưa\nChắc anh đang nhìn thời gian trôi\nKhi màu lá xanh sang mùa\nChắc anh đang hẹn hò chung đôi\nYêu đương chiều tối\nVà rồi em biết để làm gì (biết để làm gì)\nChẳng thể cùng sẻ chia\nCó bao nhiêu khoảng cách\nEm mong được lấp đầy\nAnh ơi!\nMà anh biết không? (anh biết không?)\nNhớ thương chìm trong bão giông (trong bão giông)\nBỏ lại em\nVang lên câu ca cho ngàn người xem\nCó những nỗi đau khi yêu không mang tên này\n(Có những nỗi đau khi yêu không mang tên này)\nGiờ em biết sao cho vừa\n(Giờ em biết sao cho vừa)\nThật lòng rằng em rất nhớ\nAnh của ngày xưa\nCó những nỗi đau khi yêu không mang tên này\n(Có những nỗi đau khi yêu không mang tên này)\nGiờ em biết sao cho vừa\n(Giờ em biết sao cho vừa)\nThật lòng rằng em rất nhớ\nAnh của ngày xưa\nMà giờ em biết để làm gì (biết để làm gì)\nChắc anh đang vui', 'Chắc anh đang , Tiên Tiên , Trang , Indie', 0),
(7, 'Cho tôi tình yêu', 'Denn', '637af4546d32b.mp3', '637af4546d32f.jpg', 'Mặt trời lấp ló trên ô cửa sổ\nNgày đang tới trong những câu chuyện\nNhẹ nhàng em hát vu vơ đôi lời\nLòng tôi ngây ngất say mê bồi hồi\nCứ thế tôi nhớ nhung nụ cười\nCứ thế tôi vấn vương điệu nhạc\nChỉ một giây rơi vào ánh mắt\nLà cả thế giới thôi xoay vòng\nEm cho tôi tình yêu, cho tôi tình yêu\nEm cho tôi câu hát xanh\nNhư ngày mùa sang\nEm cho tôi tình yêu, cho tôi tình yêu\nEm cho tôi hơi ấm êm khi đời lạnh giá\nEm cho tôi tình yêu, cho tôi tình yêu\nEm cho tôi những đắm say\nNgọt ngào đôi môi\nEm cho tôi tình yêu, cho tôi tình yêu\nEm cho tôi tình yêu, cho tôi tình yêu\nCứ thế tôi nhớ nhung nụ cười\nCứ thế tôi vấn vương điệu nhạc\nChỉ một giây rơi vào ánh mắt\nLà cả thế giới thôi xoay vòng\nEm cho tôi tình yêu, cho tôi tình yêu\nEm cho tôi câu hát xanh\nNhư ngày mùa sang\nEm cho tôi tình yêu, cho tôi tình yêu\nEm cho tôi hơi ấm êm khi đời lạnh giá\nEm cho tôi tình yêu, cho tôi tình yêu\nEm cho tôi những đắm say\nNgọt ngào đôi môi\nEm cho tôi tình yêu, cho tôi tình yêu\nEm cho tôi tình yêu, cho tôi tình yêu', 'Cho tôi tình yêu , Denn , Indie , Nhạc trẻ', 0),
(8, 'Chơi vơi', 'Thái Đinh, NamKun', '637af4944767a.mp3', '637af4944767e.jpg', 'Chơi vơi trong chiều nay đường về vắng ai\nÁnh dương tà một mình sương gió mong ai ghé lại\nEm đi đâu về đâu tình còn như xưa\nChút mơ hồ thầm thì bên tai khó phai\nMuôn thanh âm đan tơ tình ta hoá mê\nNgày em đi trong cơn vô liêu hoa tím buồn thay\nBao uyên ương chung đôi thanh xuân mua vui má vai kề\nNgười quay lưng khăn ai nâng túi sờn dây\nTrao con tim đi trước nước mắt về sau\nThuyền không trôi vô tâm vô tình mông lung bến sầu\nĐường em xuôi anh xin nhường lối đắng thấu lòng nhau\nTình nhòe phai hong khô treo gió luồn sâu\nThương thân hoa lan tím quý phái tình chung\nHồ điệp kiêu sa nay ba đào mênh mông sớm tàn\nMàn đêm đen em soi tình ái dưới đáy mê cung\nTìm anh trong lưu niên vang âm tiếng than\nLà một đời ngang trái đoạn trường ái ân muôn phần\nNgao du khắp bốn phương nhưng nay lạc ngã đường\nLời thì thầm em nói như hương khẽ ngang qua đây\nĐể ta mơ giấc mơ từ ngày người đi\nTrao con tim đi trước nước mắt về sau\nThuyền không trôi vô tâm vô tình mông lung bến sầu\nĐường em xuôi anh xin nhường lối đắng thấu lòng nhau\nTình nhòe phai hong khô treo gió luồn sâu\nThương thân hoa lan tím quý phái tình chung\nHồ điệp kiêu sa nay ba đào mênh mông sớm tàn\nMàn đêm đen em soi tình ái dưới đáy mê cung\nTìm anh trong lưu niên vang âm tiếng than', 'Thái Đinh , NamKun , Nam Kun , Chơi vơi , Indie , Nhạc trẻ', 0),
(9, 'Chuyện Thu', 'Minh Cà Ri, Huy Lê', '637af4cb21891.mp3', '637af4cb21894.jpg', 'Verse:\n\nMây lặng ôm giấc mơ\n\nGió từng cơn khẽ ru\n\nLá rơi vàng một chiều Cư Xá\n\nMùa thu.\n\nĐôi bàn tay thoáng lơi\n\nMà vô tình lạc mất nhau\n\nMột đời\n\nNụ cười lúc xưa\n\nGiờ phai nhòa theo tiếng mưa.\n\nChorus:\n\nCon đường ta đã qua\n\nMà sao giờ đây hóa lạ\n\nAnh nhớ vòng tay phía sau\n\nDịu dàng biết bao.\n\nvài ba khúc Ca ngày xưa anh viết\n\nHát cho em đôi ba lần\n\nGiờ cũng theo mây trôi thật xa.\n\nChorus:\n\nĐôi tình nhân đón đưa\n\nChạy theo từng cơn gió mùa\n\nTrên lá giọt sương sớm mai\n\nCòn lưu luyến ai.\n\nmột hai bước Chân chẳng còn quen lối\n\ntừng Chiếc lá rơi như vẫy chào\n\nChào chuyến xe đi qua…\n\nMây lặng ôm giấc mơ\n\nGió từng cơn khẽ ru\n\nNắng ươm vàng thoảng hương hoa sữa\n\nMùa thu.\n\nEm nhẹ ôm lấy anh\n\nRằng “anh đừng lo, khó khăn\n\nQua rồi.”\n\nBàn tay khẽ đan\n\nVà câu chuyện thôi rẽ ngang.', 'Chuyện Thu , Minh Cà Ri , Huy Lê', 0),
(10, 'Có gì đâu', 'NamKun', '637af51386875.mp3', '637af5138687a.jpg', 'Và mình chia tay\nAnh đâu có biết sẽ ra thế này\nĐâu đó ngoài kia thằng Kiên đang hát khi hôm nay thành ngày xưa (và bầu trời luôn)\nTa qua được chuyện này chưa hay thêm một vài ngày nữa\nLy Lipton sữa trên bàn giờ được thay thế bởi một cốc cà phê nâu\nAnh vẫn ngẩn ngơ chán chường không biết não mình đang ngủ hay là đi đâu yo\nVà nếu mỗi tối điện thoại thôi rung vì những cuộc gọi của em\nAnh sẽ bình thản tắt máy mà chẳng đợi chờ điều gì tới quá nửa đêm\nChiếc khóa cửa thêm một lần đổi số đầu óc anh lại một lần ngu đi\nCố nhớ đôi điều mới mẻ dù gì cũng muốn quên luôn những điều cũ kĩ\nAnh vẫn bắt đầu ngày mới với múi giờ là 11h trưa\nVẫn than thở ngày nắng gắt vẫn lười biếng lúc trời mưa\nVì anh vẫn không hào hứng nếu ra đường mà chẳng có ai chờ\nDù sao anh cũng có vài chiến hữu rủ rê Dota đến 2h\nƠ sai nhờ anh vẫn còn bản thân để yêu thương\nAnh còn bận tăng lên 70 kí thì giờ đâu buồn chuyện yêu đương\nAnh còn bận viết thêm vài bài nhạc sến để bọn trẻ con đem tỏ tình\nVà tất nhiên là anh đã thôi cau có để giữ cho mình đừng khó tính\nCó gì đâu vài giờ không nhau anh thưởng cho mình thêm giấc ngủ\nCó gì đâu đường về thêm mau anh thả mình vào thói quen cũ\nVà có gì đâu có gì đâu\nChỉ là không em lòng anh trống rỗng vậy nên tâm trí anh có gì đâu oh\nCó gì đâu oh có gì đâu oh\nChỉ là không em lòng anh trống rỗng vậy nên tâm trí anh có gì đâu', 'Có gì đâu , NamKun , Nam Kun , Indie , Nhạc trẻ', 0),
(11, 'Có những chiều', 'Thái Đinh, Minh Cà Ri', '637af593af1f9.mp3', '637af593af1fb.jpg', 'Rồi một chiều cuối thu\nGió maу\nThả vào nỗi nhớ\nHao gầу\nƁản nhạc nơi quán quen\nϹất lên\nϹhuуện tình xưa cũ.\nGiọt cà phê khẽ rơi\nVỡ đôi\nϹhiếc phin đậm đen\nĐắng buồn\nϹhuуện tình ai vỡ tan\nϹhiếc ôm\nƊở dang.\nϹhorus\nLiệu rằng em có nhớ về anh\nϹó biết rằng anh\nVẫn đang một mình\nƝgồi giữa bao người\nRồi cà phê cũng nguội ngắt\nTàn thuốc gần tắt\nMà em vẫn nơi phương trời.\nƊù cho em chẳng nhớ về anh\nϹhẳng biết rằng anh\nGiấu trong tiếng đàn\nƁao lời уêu chứa chan\nRồi đông cũng sẽ dần qua\nƝgàу không còn xa\nHình bóng ai phai nhòa.\nVerse:\nRồi một chiều cuối đông\nHững hờ\nKìa làn khói thuốc\nLững lờ\nLặng nhìn mâу khẽ trôi\nƝgang trời\nƁài ca buông lơi.\nVà hỏi rằng nắng ơi\nƝắng mang\nƐm đi về đâu\nGiữa đời?\nƁỏ lại bao giấc mơ\nKhúc ca\nLời thơ.\nϹhorus:\nLiệu rằng em có nhớ về anh\nϹó biết rằng anh\nVẫn đang một mình\nƝgồi giữa bao người\nRồi cà phê cũng nguội ngắt\nTàn thuốc gần tắt\nMà em vẫn nơi phương trời.\nƊù cho em chẳng nhớ về anh\nϹhẳng biết rằng anh\nGiấu trong tiếng đàn\nƁao lời уêu chứa chan\nRồi đông cũng sẽ dần qua\nƝgàу không còn xa\nHình bóng ai phai nhòa.\nƁridge:\nVà một ngàу em thương người ta\nVui bên người ta\nЅáng trưa hẹn hò\nϹhiều tối Xofa\nThì anh mong cho người ta\nϹhẳng уêu gần xa\nϹhỉ thương mỗi em thôi mà.\nƊù cho em chẳng nhớ về anh\nϹhẳng biết rằng anh\nGiấu trong tiếng đàn\nƁao lời уêu chứa chan\nRồi đông cũng sẽ dần qua\nƝgàу không còn xa\nHình bóng ai phai nhòa.\nVà hỏi rằng nắng ơi\nƝắng mang\nƐm đi về đâu\nGiữa đời?\nϹòn anh ôm giấc mơ\nƝgóng trông\nƝgẩn ngơ.', 'Có những chiều , Thái Đinh , Minh Cà Ri', 0),
(12, 'Đâu có sao', 'Judian, Haohinh', '637af5eb9f4f0.mp3', '637af5eb9f4f3.jpg', 'Verse 1:\n\nLang thang tới lui chẳng đến đâu\n\nVì đâu cũng là thế\n\nYêu đương cũng chẳng đến đâu\n\nThì thôi ta một mình\n\nPre-chorus:\n\nĐời là thế, ngày dài thế\n\nChỉ một mình thôi\n\nĐời là thế, người là thế\n\nThì thôi đến đây thôi\n\nChorus:\n\nĐâu có sao mà\n\nTình yêu giờ đây quá mệt\n\nĐâu có chi mà\n\nGiờ chẳng cần ai kề bên\n\nMột lần thôi chẳng muốn thêm\n\nTrách chi người ta quá đáng\n\nMột người chẳng muốn có em\n\nNhưng hàng trăm người chờ ngoài kia\n\nĐừng lo thêm nhé babe\n\nGiờ em chẳng là của ai\n\nChờ đợi chi somebody\n\nTình yêu chẳng là gì đâu\n\nVerse 2:\n\nHôm nay đi qua chốn đây\n\nTình yêu đã xa ngày đó\n\nKhông ai quan tâm đúng sai\n\nChẳng ai nhớ mong điều gì\n\nPre-chorus:\n\nĐời là thế, ngày dài thế\n\nChỉ một mình thôi\n\nĐời là thế, người là thế\n\nThì thôi đến đây thôi\n\nChorus:\n\nĐâu có sao mà\n\nTình yêu giờ đây quá mệt\n\nĐâu có chi mà\n\nGiờ chẳng cần ai kề bên\n\nMột lần thôi chẳng muốn thêm\n\nTrách chi người ta quá đáng\n\nMột người chẳng muốn có em\n\nNhưng hàng trăm người chờ ngoài kia\n\nĐừng lo thêm nhé babe\n\nGiờ em chẳng là của ai\n\nChờ đợi chi somebody\n\nTình yêu chẳng là gì đâu\n\nChẳng là gì đâu\n\nChẳng là gì đâu\n\nNày em ơi, cuộc sống mà\n\nChẳng là gì đâu\n\nChẳng có chi đâu\n\nTrái ngang là thế cớ sao mà em buồn..\n\nChorus 2:\n\nĐâu có sao mà\n\nTình yêu giờ đây quá mệt\n\nĐâu có chi mà\n\nGiờ chẳng cần ai kề bên\n\nĐoạn tơ duyên đến đấy thôi\n\nNhắc chi chuyện xưa đã hết\n\nVài ba câu dối trá kia\n\nLàm em yêu người một thời\n\nĐừng tin ai nữa babe\n\nMộng mơ sẽ không thành đâu\n\nNgày mai giông tố sẽ qua\n\nRồi em sẽ lại bình yên.', 'Đâu có sao, Judian , Haohinh', 0),
(13, 'Đông kiếm em', 'Vũ', '637af642a773b.mp3', '637af642a7740.jpg', 'Tôi hát cho màu xanh mãi xanh\nCho một người lặng im biết yêu\nVà tôi viết cho mùa yêu xốn xang\nCho một đời nhớ thương vẹn nguyên\nCô đơn đến thế\nMưa rơi lách tách kì cục đợi ai\nSâu trong ánh mắt\nTôi ngu ngơ mơ thời gian dừng trôi\nCòn lại đây nhớ mong còn lại tôi với ai\nGiờ này em chắc đang ngủ say\nHay là em còn đang khóc một mình\nNhư làn sương muộn màng\nLạc trong đêm con tim em lạc trong đêm\nLòng phiêu du nhớ em mùa thu đã đi qua\nĐông kiếm em mùa đông kiếm em\nHuh hah\nMùa đông kiếm em đông kiếm em\nTôi biết em sợ đông sẽ tan\nEm lạ lùng gọi trong vô vọng\nVà tôi nhớ ly cà phê sắp tan\nBiết bao giờ là em sẽ về\nCô đơn đến thế\nMưa rơi lách tách kì cục đợi ai\nSâu trong ánh mắt\nTôi ngu ngơ mơ thời gian dừng trôi\nCòn lại đây nhớ mong còn lại tôi với ai\nGiờ này em chắc đang ngủ say\nHay là em còn đang khóc một mình\nNhư làn sương muộn màng\nLạc trong đêm con tim em lạc trong đêm\nLòng phiêu du nhớ em mùa thu đã đi qua\nĐông kiếm em mùa đông kiếm em\nHuh hah\nMùa đông kiếm em đông kiếm em\nCòn lại tôi với ai\nCòn lại bao nhớ mong\nGiờ này em chắc đang ngủ say', 'Đông kiếm em , Vũ , Indie , Nhạc trẻ', 0),
(14, 'Em', 'NamKun', '637af674c8227.mp3', '637af674c822a.png', 'Anh, ngồi vẽ nên từng giấc mơ\nKhẽ đắm chìm trong những khúc nhạc còn vẩn vơ\nNgày trôi những câu hát êm đềm\nKhi anh viết lên tên EM\nEm, nhiều nghĩ suy chẳng nói nên\nDù có lúc môi buông lời thở than vì mỏi mệt\nDù ngày trôi nhiều giây buồn đau\nVà những phút chốc chẳng thấy nhau\nPre- chorus :\nKhó khăn vẫn như nặng thêm, bờ vai em quá bé nhỏ để lắng lo hằng đêm\nKhi bàn chân em chẳng muốn bước giữa muộn phiền\nHãy tựa vai anh anh ánh\nChorus :\nEm là giọt nắng đã luôn sưởi ấm anh\nLà chợt sương anh níu giữ bên cạnh\nLà những nốt nhạc lửng lơ của bài hát anh từng mơ\nDù đôi khi là mưa trên khóe mắt\nXin ngày đừng mang đi khoảnh khắc ta nắm tay nhau\nXin tháng hãy giữ tiếng yêu đến mãi sau\nVì dẫu bão giông ngoài xa, lòng anh vẫn mang bài ca\nLà EM', 'Em , NamKun , Nam Kun , Indie , Nhạc trẻ', 0),
(15, 'Gió vẫn hát', 'Long Phạm', '637af6bf412e9.mp3', '637af6bf412ec.jpg', '… Thương thì thương thế thôi\nBiết bao đêm dài lòng anh ngóng trông\nỞ nơi ấy phía xa xa đại dương\nTrái đất vẫn xoay vẫn xoay tròn hai người yêu nhau\nChờ mong đến một ngày thuộc về nhau\n… Anh vẫn đứng đây bên khung cửa sổ\nAnh vẫn đứng đây chờ nắng lên\nCòn em giờ đang nơi đâu có thấy chăng mùa nắng đã ghé vai gầy\nNgười yêu hỡi anh nhớ tiếng em à ơi\n… Gió vẫn hát thành lời\nMặc kệ mây mây bay về trời\nỞ nơi ấy gió lay buồn biết bao nhiêu\nNhững nỗi nhớ một thời\nNgười đi xa bên hiên sao không về đây\nNgười yêu hỡi hãy quay về với anh\n… Bao ngày anh ngóng trông đã bao đêm rồi anh vẫn ngóng trông\nỞ nơi ấy phía xa xa trùng mây\nBao lời anh hát lên trái tim anh dành trao đến em\nNgười yêu hỡi anh yêu riêng mình em thôi\n… Gió vẫn hát thành lời\nMặc kệ mây mây bay về trời\nỞ nơi ấy gió lay buồn biết bao nhiêu\nNhững nỗi nhớ một thời\nNgười đi xa bên hiên sao không về đây\nNgười yêu hỡi hãy quay về với anh\n… Tara oh\nTình yêu ấy anh vẫn chỉ dành trao riêng em mà thôi\nDù ngày mai bão giông ngập trời\nThì tình anh trao em mãi mãi\nNgười yêu hỡi anh chỉ yêu riêng mình em thôi\n… Gió vẫn hát thành lời\nMặc kệ mây mây mây bay về trời\nỞ nơi ấy gió lay buồn biết bao nhiêu\nNhững nỗi nhớ một thời\nNgười đi xa bên hiên sao không về đây\nNgười yêu hỡi hãy quay về với anh\nNgười yêu hỡi hãy quay về với anh', 'Gió vẫn hát , Long Phạm , Indie , Nhạc trẻ', 0),
(16, 'Gửi chúng ta năm nào', 'Cao Minh', '637af7053b16a.mp3', '637af7053b16e.jpg', 'Này tôi ơi, sao vẫn còn ở đây\nKỷ niệm đang trôi đấy\nTôi có nhớ lời hẹn hôm nay\nEm ngơ ngác chờ\nGương mặt ngây thơ\nChờ một chút một chút thôi nhé\nTôi chắc đang kẹt xe\nChiều hoàng hôn nhiều gió\nTôi về cùng mùa thu\nRộn ràng từng con phố\nKhông ai giống như bọn tôi\nTrêu trọc những người qua đường\nHát vang một góc trời\nTừng ngày trôi đi như thế\nEm đã ở lại tim này\nCũng có lúc muốn nghe lại\nTiếng em la mắng dịu dàng\nLòng bồi hồi lo lắng\nMỗi khi chạm tóc nàng\nCũng có lúc muốn quay về\nĐể bạn bè trêu hai ta như là một đôi\nVậy mà khi ấy tôi đã phản đối rất dữ dội\nHình như em không biết không biết\nEm là giấc mơ của tôi của tôi\nChỉ là giấc mơ mà thôi mà thôi\nBao đêm dài tôi đã mơ\nHình như em không biết không biết\nCho đến những tháng năm về sau\nMỗi khi nhớ về em về em\nTôi đều muốn quay về khi xưa\nVà rồi tôi cũng đến\nTrong bộ dạng bảnh bao\nNụ cười em khi ấy\nHôm nay đã dành cho ai rồi\nNơi đông đúc người\nEm nguyện thề trăm năm\nTừng ngày trôi đi như thế\nEm đã trở về xa xôi\nCũng có lúc muốn nghe lại\nTiếng em la mắng dịu dàng\nLòng bồi hồi lo lắng\nMỗi khi chạm tóc nàng\nCũng có lúc muốn quay về\nĐể bạn bè trêu hai ta như là một đôi\nVậy mà khi ấy tôi đã phản đối rất dữ dội\nHình như em không biết không biết\nEm là giấc mơ của tôi của tôi\nChỉ là giấc mơ mà thôi mà thôi\nBao đêm dài tôi vẫn mơ\nHình như em không biết không biết\nCho đến những tháng năm về sau\nMỗi khi nhớ về em về em\nTôi đều giận mình sao không nói hết\nEm đâu biết một người yêu em\nTìm mọi cách ở gần bên em\nEm đâu biết một người\nCoi em như là thanh xuân\nEm đâu biết một người\nCoi em như là thanh xuân\nNày tôi ơi, sao vẫn còn ở đây?', 'Gửi chúng ta năm nào , Cao Minh , Indie', 0),
(17, 'Không tên', 'Trang, Khoa Vũ', '637af7682337e.mp3', '637af76823381.jpg', 'Ngày cuối tháng năm\nTrời sa mưa nhẹ\nVà ngày sao quá đỗi dài\nTàn thuốc đã rơi\nMà anh chưa về\nLần theo làn khói cũ mờ xa\nTừng phút đắn đo\nMình em nơi tháng ngày\nĐã cuốn đi những chiều ai về\nĐầu phố đón đưa\nBàn tay dịu hiền\nVà nắng thẹn thùng trên má em hồng\nCứ yêu\nĐể nhớ thương\nTình yêu như ngàn vì sao\nRực sáng trong đêm hè\nNhững phút giây hẹn thề\nYêu anh qua ngàn cây số\nVà trách nắng rằng\nMang anh đi để em cứ hoài ngóng trông\nKìa nắng đã về\nLàm lòng em thao thức chờ mong (chadida huh ah)\nGiọt nắng khẽ rơi\nĐọng trên ô cửa sổ (cửa sổ)\nLàm lòng ai lặng ôm nỗi buồn\nMàu lá đã xanh\nMà anh chưa về (anh chưa về)\nLời yêu nay em dành cho gió sang mùa\nCứ yêu (cứ yêu)\nĐể nhớ thương\nTình yêu như ngàn vì sao (như ngàn vì sao)\nRực sáng trong đêm hè\nNhững phút giây hẹn thề\nYêu anh qua ngàn cây số (qua ngàn cây số)\nVà trách nắng rằng\nMang anh đi để em cứ hoài ngóng trông\nKìa nắng đã về\nLàm lòng em thao thức chờ mong (chadida huh ah)\nHah\nTadida papa\nYeh\nTadada papa\nTadada hah\nAh\nCứ yêu (cứ yêu)\nĐể nhớ thương\nTình yêu như ngàn vì sao (như ngàn vì sao)\nRực sáng trong đêm hè\nNhững phút giây hẹn thề\nYêu anh qua ngàn cây số (qua ngàn cây số)\nVà trách nắng rằng\nMang anh đi để em cứ hoài ngóng trông\nKìa nắng đã về\nLàm lòng em thao thức chờ mong (thao thức chờ mong anh)', 'Không tên, Trang, Khoa Vũ', 0),
(18, 'Lá thư', 'Tùng', '637af79f7392d.mp3', '637af79f73930.jpg', 'Lá Thư - Tùng\nNhạc sĩ: Tùng\n\nThể loại: Nhạc Trẻ\nĐĂNG NHẬPĐể thưởng thức chất lượng âm nhạc tốt nhất\n Yêu thíchThêm vào Tải về máyChia sẻCài nhạc chờ\nLời bài hát|\nHợp Âm Guitar\nEm, hôm nay anh mua con tem vài đồng thôi\nĐể gửi vài điều đến nơi xa xôi\nĐể chờ một điều ở nơi xa xôi\nXem ra hôm nay mưa tivi bảo là ngày giông\nMột ngày bình thường nhớ mong\nCũng chả làm gì viết cho em vài dòng\nEm, sớm nay có thức giấc như mọi ngày\nĐi làm tầm này, hay lại ngủ say\nAnh dạo này dậy sớm hơn rồi\nEm, không biết đâu\nAnh đã thấy mình hay nghĩ không đổi thay\nBỗng dưng một ngày nhìn vết sẹo trên đôi tay mình\n\nLà ngày biết trong đời\nChợt thấy mình trần trụi qua từng ngày mới\nĐã thế lâu rồi, từ lúc mình chào đời\nThế thôi, anh quên mất đôi khi\n\nMùa xuân tháng 10, trời đầy những cơn mưa đầu mùa\nBên em trời đã mát hơn chưa?\nBên đây cơn mưa thì cứ đùa cả ngày\nLoài người vẫn vậy\nAnh thấy anh bên này,\nVẫn vậy, vẫn chạy, vẫn quay đều, quay\nHôm nay vô tình, anh bỗng tự hỏi mình\nRằng điều gì làm hành tinh mình quay?\nBiết đâu câu trả lời,\nAnh bỗng thấy em cười trong tấm hình đã lâu rồi, kẹp hờ thôi\n\nLà ngày biết trong đời,\nCòn thấy những mong đợi qua từng ngày mới\nĐã thế lâu rồi, từ trước khi chào đời\nThế thôi, anh quên mất đôi khi\n\nMà biết không em,\nDù chữ xấu nhưng anh vẫn viết tay về ngày tháng hôm qua quên nắm tay\nLà ngày biết trong đời, được thấy một nụ cười qua từng ngày mới\nĐã thế lâu rồi, từ lúc em chào đời.\n', 'Lá thư , Tùng, Indie , Nhạc trẻ', 0),
(19, 'Lấm Lem', 'Hải Sâm', '637af7e914945.mp3', '637af7e91494f.jpg', 'Anh về\nThầm mong nhớ màu hoàng hôn lấm lem\nHay câu ca đã cũ mềm\nVẫn chưa từng\nCùng em trên những con đường\nEm về\nĐừng mong nhớ nhiều về những giấc mơ\nXin cho anh những thẫn thờ\nGiấu trong lòng\nMà em chưa nói bao giờ\nVà nếu lúc ấy\nXin người đừng quên giây phút này\nNgày mình còn bên cạnh nhau\nAnh không muốn mất em\nVà nếu lúc ấy\nTrên bầu trời xanh như thế này\nLiệu bầu trời có còn xanh\nQua cơn giông bão kia tồn tại\nEm về\nĐừng mong nhớ nhiều về những giấc mơ\nXin cho anh những thẫn thờ\nGiấu trong lòng\nMà em chưa nói bao giờ\nVà nếu lúc ấy\nXin người đừng quên giây phút này\nNgày mình còn bên cạnh nhau\nAnh không muốn mất em\nVà nếu lúc ấy\nTrên bầu trời xanh như thế này\nLiệu bầu trời có còn xanh\nAnh không muốn mất em mãi mãi\nChỉ còn lại những cuốn phim\nVà nếu lúc ấy\nXin người đừng quên giây phút này\nNgày mình còn bên cạnh nhau\nAnh không muốn mất em\nVà nếu lúc ấy\nBầu trời xanh như thế này\nLiệu bầu trời có còn xanh\nQua cơn giông bão kia, tồn tại\nSau này hoàng hôn vẫn\nMột màu vương lấm lem\nĐem tâm tư ra trước thềm\nĐến bao giờ\nBầu trời kia tan vào mãi mãi', 'Lấm Lem , Hazy , Hải Sâm , Indie', 0),
(20, 'Làm một chiếc trà sữa không', 'NamKun', '637af890365c3.mp3', '637af890365c7.jpg', 'Một ngàу trên môi em nụ cười bỗng tan biến\nƁộ mặt chợt toát mỗi 2 chữ đó là ưu phiền\nƁầu trời như xám đen\nLòng anh u ám thêm\nϹhợt hiện suу nghĩ , làm một chiếc trà sữa không ?\nƁ\nMột ngàу khi nỗi buồn em chợt xanh như cành lá\nHoặc chỉ là do làm chưa được nhanh rồi bị sếp la\nVà rồi em bỗng cáu mỗi đêm\nϹhỉ vì anh chẳng hiểu nổi em\nThì em có muốn, làm một chiếc trà sữa không ?\nPre chorus :\nĐàn ông bọn anh chẳng tinh tế, chẳng chi li, chẳng nhiều điều\nϹhỉ biết chở che mỗi cho em, là người уêu\nVậу nên buồn vu vơ haу khóc, trái tim người chớ mỏng manh\nƁỡi ở đâу, có anh\nϹhorus:\nTừng ngàу anh đau đầu, vì thấу em u sầu\nTừ nỗi buồn qua ngàу không gì để mặc\nAnh thì chẳng thể để mặc, đành đối phó với những nỗi lo của em\nVà người đừng im lặng, mà hãу luôn tin rằng\nTrà sữa làm tinh thần ta thêm cân bằng\nƝên đừng lo chuуện cân nặng\nƝàу em ơi, đi theo anh không sợ béo\nLàm một chiếc trà sữa không ?\n\nVerse:\nϹ\nVà nàу em ơi đừng ôm thêm nghĩ suу phiền não\nRằng trà sữa sẽ làm em phải béo lên nhiều biết bao\nThì đừng lo sẽ có anh luôn\nϹhạу bộ cùng em mỗi khi buồn\nVậу thì em hỡi, làm một chiếc trà sữa thôi ?\nPre chorus :\nĐàn ông bọn anh chẳng tinh tế, chẳng chi li, chẳng nhiều điều\nϹhỉ biết chở che mỗi cho em, là người уêu\nVậу nên buồn vu vơ haу khóc, trái tim người chớ mỏng manh\nƁỡi ở đâу, có anh\nϹhorus:\nTừng ngàу anh đau đầu, vì thấу em u sầu\nTừ nỗi buồn qua ngàу không gì để mặc\nAnh thì chẳng thể để mặc, đành đối phó với những nỗi lo của em\nVà người đừng im lặng, mà hãу luôn tin rằng\nTrà sữa làm tinh thần ta thêm cân bằng\nƝên đừng lo chuуện cân nặng\nƝàу em ơi, đi theo anh không sợ béo\nLàm một chiếc trà sữa không ?\n\nMột ngàу em bất chợt vui, chẳng thiết tha trà sữa\nLòng anh bối rối chẳng biết phải nói ra sao cho vừa\nMạnh dạn đành tự thú với em\nThật lòng anh thấу vẫn rất thèm\nVậу thì em hỡi, làm một chiếc trà sữa không\n\nVậу thì em hỡi, làm một chiếc trà sữa không\n\nMỗi khi uống trà sữa, hãу nghe bài nàу một lần để trấn an bản thân rằng trà sữa không béo đâu, thế thì sẽ ngon miệng hơn, nhé.', 'Làm một chiếc trà sữa không , NamKun , Nam Kun , Indie , Nhạc trẻ', 0),
(21, 'Loanh Quanh', 'Mademoiselle', '637af8d23ef99.mp3', '637af8d23ef9c.png', 'Có một chiều tôi đi theo anh\nLoanh quanh loanh quanh đi khắp phố phường\nThì thầm đọc tên những con đường\nGió lùa qua mái tóc xem nắng nhuộm vàng trên hàng cây già\nBước từng bước thật chậm\nAnh không muốn dừng chân còn tôi chưa muốn về nhà\nCũng mặt trời treo trên mây cao\nSao mặt trời anh không mang nắng hạ\nMàu hoàng hôn trên lá anh cũng đâu thiết tha\nDòng người đi qua hối hả phải chăng anh không mặn mà\nNếu tôi có nhạt nhòa trong tâm trí anh cũng đâu bất ngờ\nHum hum\nBiết đời này còn lại bao nhiêu\nTôi cứ yêu yêu qua các mùa\nKhát khao như nắng ban trưa\nNghĩ suy như gió như mưa\nThích anh luôn ở bên tôi\nMuốn anh riêng tôi mà thôi\nMà chờ đợi quá lâu rồi tôi đâu sống như mây trời\nCâu chuyện tình một thời xin anh hãy buông lơi\nVà cho tôi một con đường\n', 'Loanh Quanh , Mademoiselle , Indie , Nhạc trẻ', 0),
(22, 'Lời thì thầm của gió', 'Cheng', '637af913c3b46.mp3', '637af913c3b4a.jpg', 'Anh nhờ con phố\nGiữ giùm anh bao nhiêu ngày thơ\nEm về đây không nói đi...anh còn chờ\nKìa những giấc mơ vẫn đòi vỗ về\nBởi tim anh chưa thể\ncài then nỗi nhớ cho đêm dài thôi chẳng còn bất ngờ.\n\nTại sao em vội buông cánh tay\nKhi vẫn yêu anh như ngày ấy?\nĐể giờ bơ vơ hai đứa tội lắm em à...\nMình từng ngược gió để cuộn lấy nhau\nNhưng duyên trời ai có thấu\nChẳng một lời, người tạ từ\nThôi mình anh.\n\nĐành thì thầm lời của gió\nLòng này người tường hay chưa?\nBiết yêu em mấy cho vừa?\nĐành thì thầm lời của gió\nTình mình đẹp tựa khúc ca\nNhưng cũng chỉ là hôm qua.\n\n[Bridge:]\nLiệu khi một mai ta hoá gió mây\nEm có xót xa cho những tháng ngày ấy?\nCòn anh sẽ chẳng hối tiếc\nVì cũng đã yêu hết lòng\nVậy thôi thì anh gom hết chân thành\nChôn thật sâu nơi trái tim kia mỏng manh\nRồi tập quên đi.\n\nĐành thì thầm lời của gió\nLòng này người tường hay chưa?\nTâm tư này biết gửi trao cho ai đây em?\nKhi đông vừa đến, tình mình, cũng chỉ là hôm qua.', 'Lời thì thầm của gió , Cheng', 0),
(23, 'Một đêm say', 'Thịnh Suy', '637af95e88f9f.mp3', '637af95e88fa9.jpg', 'Khi đôi môi em còn đỏ mọng\nEm muốn nói em yêu anh\nKhi men còn trong hơi thở\nLại gần hôn anh đi\nKhi con tim không còn trên đầu\nKhi hai má em hây hây\nEm nói em say tiếng đàn\nVậy lại gần hôn anh đi\nLại gần hôn anh\nAnh sẽ để em mặt trời\nLại gần hôn anh\nHay em để anh chơi vơi\nGiờ còn đôi ta\nKia là núi đây là nhà\nGiờ còn đôi ta\nEm có muốn đi thật xa\nTa chỉ sống một lần trên đời\nSuy nghĩ lắm chi em ơi\nBao nhiêu yêu thương trên đời\nThành vị ngọt trên đôi môi\nLại gần hôn anh\nAnh sẽ để em mặt trời\nLại gần hôn anh\nHay em để anh chơi vơi\nGiờ còn đôi ta\nKia là núi đây là nhà\nGiờ còn đôi ta\nEm có muốn đi thật xa\nLại gần hôn anh\nAnh sẽ để em mặt trời\nLại gần hôn anh\nHay em để anh chơi vơi\nGiờ còn đôi ta\nKia là núi đây là nhà\nGiờ còn đôi ta\nEm có muốn đi thật xa\nKhi đôi môi em còn đỏ mọng\nEm muốn nói em yêu anh\nKhi men còn trong hơi thở\nLại gần hôn anh đi\nKhi đôi môi em còn đỏ mọng\nKhi anh nói anh yêu em\nKhi anh ta còn say giấc nồng\nLại gần hôn anh đi', 'Một đêm say , X , Thịnh Suy , Indie , Nhạc trẻ', 0),
(24, 'Ngơ Ngác', 'Sulla, Thế Bảo', '637af99990d39.mp3', '637af99990d3d.jpg', 'Em ngơ ngác đứng chờ\nAnh ngơ ngác hững hờ\nTa ngơ ngác nên lạc nhau mãi\nAnh đã hứa nhưng anh chẳng tới\nĐể em đứng đợi đợi mãi đợi hoài\nEm ngơ ngác giữ lời\nNên em vẫn đứng đợi\nNhưng không nói cho anh một câu\nEm đã hứa sẽ hát như một lời tỏ tình\nNên em hát tan nát lòng mình\nVà anh đã quên em\nĐã quên đi khúc ca anh từng viết\nVà anh đã xa rồi\nChẳng giữ lời\nĐã yêu thêm một người\nAnh ngơ ngác giữa đời\nGiữa những thứ quá xa vời\nNhưng chưa nói cho em một câu\nAnh đã hứa sẽ viết nên\nMột câu chuyện tình\nNhưng anh viết đoạn kết một mình\nVà anh vẫn mong em\nVẫn chưa quên khúc ca em từng viết\nVì anh vẫn yêu em\nVẫn chưa thôi\nVấn vương bên một người\nVà em sẽ quên anh\nSẽ quên đi khúc ca em từng viết\nVà anh vẫn yêu em\nVẫn chưa thôi\nVấn vương bên một người\nVà em đã quên anh\nĐã quay lưng để yêu một người khác\nDù em đã quên anh\nĐã thôi buồn vì khúc ca ngày nào\nVà anh vẫn bên em\nVẫn mong em\nVẫn yêu em', 'Ngơ Ngác , Sulla , Thế Bảo , Indie , Nhạc trẻ', 0),
(25, 'Tình cũ', 'Harrie', '637af9c842c00.mp3', '637af9c842c02.jpg', 'Người nào đó, em làm cho anh hóa điên lúc này\nVài lời nói , đã đánh mất trái tim em rồi\nGiờ chia tay, phải làm sao để em quay về\nTừ nay, rời xa, em\n\nNhư trong cơn say, một giây nhớ về\nHình bóng em, sao cứ hoài mong nhớ (biết em giờ phương trời nao anh chờ )\nChia tay bao lâu thì vẫn nhớ về\nNgười biết không, trái tim này đau quá (khi không có em bên canh lúc này)\n\nĐi nơi đâu, khi bên anh không phải là em nữa rồi\nChơi vơi nơi, ta buông lơi mặc cho thời gian cứ trôi (nơi đây mình anh)\nBae i miss you so, everything on my mind\nXa nơi đây, như mây trôi lạc vào trong giấc mơ ( nơi đó có em)\n\n\nLàm sao khi trong tim anh đây là cuộc tình cũ\nLàm sao cho thời gian ngừng trôi khi chúng ta bên cạnh nhau (quay về như lúc đầu)\nRồi bao năm dần trôi khi ta giờ là tình cũ\nLời yêu kia liệu có đổi thay, đôi mắt u sầu vì ai\n\nMột hai năm qua , thời gian trôi qua, từ khi đôi ta đã rời xa\nAnh nhớ về, kí ức xưa, như là một giấc mơ anh bên em lúc này\nLúc này, lúc này, anh nhớ đến em lúc này, lúc này, anh\n\nNhư trong cơn say, một giây nhớ về\nHình bóng em, sao cứ hoài mong nhớ (biết em giờ phương trời nao anh chờ )\nChia tay bao lâu thì vẫn nhớ về\nNgười biết không, trái tim này đau quá (khi không có em bên canh lúc này)\n\nĐi nơi đâu, khi bên anh không phải là em nữa rồi\nChơi vơi nơi, ta buông lơi mặc cho thời gian cứ trôi (nơi đây mình anh)\nBae i miss you so, everything on my mind\nXa nơi đây, như mây trôi lạc vào trong giấc mơ ( nơi đó có em)\n\nLàm sao khi trong tim anh đây là cuộc tình cũ\nLàm sao cho thời gian ngừng trôi khi chúng ta bên cạnh nhau (quay về như lúc đầu)\nRồi bao năm dần trôi khi ta giờ là tình cũ\nLời yêu kia liệu có đổi thay, đôi mắt u sầu vì ai', 'Tình cũ , Harrie , Indie , Nhạc trẻ', 0),
(26, 'Tình đầu', 'RHY', '637af9f8bac37.mp3', '637af9f8bac3a.jpg', 'Giọt nước rơi đọng khóe môi\nTình yêu đầu tiên sẽ luôn chia lìa\nChẳng trách ai kỷ niệm rồi sẽ phai\nĐến khi đông tàn\nƯớc mong tìm được nắng mai\nThời gian trôi khiến trước sân đầy hoa\nLiệu rằng em có vấn vương tình ta\nHay chỉ là vài đêm ưu tư thoáng qua\nNgày qua theo gió cuốn đi mộng mơ\nĐể anh ngồi ôm nỗi nhớ vẩn vơ\nSao phút ban đầu\nKhông giống đôi ta lúc này\n\nTình đầu là chia tay\nCó mấy ai yêu đến tận cùng\nHẹn thề ngày xưa vỡ như mộng\nVậy mà còn vương vấn\nĐến bây giờ mãi về sau\nƯớc mong sẽ mãi như lần đầu\n\n\nNgười đến sau nhận nỗi đau\nTại sao còn vương phút ban đầu\nChỉ trách ta không thể nào bước qua\nBóng ai u sầu\nNhớ thương tình đầu quá lâu\nThời gian trôi khiến trước sân đầy hoa\nLiệu rằng em có vấn vương tình ta\nHay chỉ là vài đêm ưu tư thoáng qua\nNgày qua theo gió cuốn đi mộng mơ\nĐể anh ngồi ôm nỗi nhớ vẩn vơ\nSao phút ban đầu\nKhông giống đôi ta lúc này\n\n\nTình đầu là chia tay\nCó mấy ai yêu đến tận cùng\nHẹn thề ngày xưa vỡ như mộng\nVậy mà còn vương vấn\nĐến bây giờ mãi về sau\nƯớc mong sẽ mãi như lần đầu\nTình đầu là chia tay\nCó mấy ai yêu đến tận cùng\nHẹn thề ngày xưa vỡ như mộng\nVậy mà còn vương vấn\nĐến bây giờ mãi về sau\nƯớc mong sẽ mãi như lần đầu\nƯớc mong sẽ mãi như lần đầu', 'Tình đầu , RHY , Indie , Nhạc trẻ', 0),
(27, 'Tôi và em', 'Pink Prog', '637afa2937811.mp3', '637afa2937814.jpg', 'Đời buồn, người tìm đến ta\nÔi thế giới diệu kỳ, chẳng ai chững lại\nĐể khóc cho nỗi buồn em\nĐời buồn, người chỉ tìm đến ta\nÔi thời gian diệu kỳ, lòng người diệu kỳ\nLặng lẽ đổi thay nơi ngày mai\nTôi và em giống như hai người điên đang cuồng si\nGiữa những bộn bề đời\nEm và tôi giống như hai người dưng đã lạc nhau\nGiữa những bộn bề đời tôi\nĐời cười, người cười với nhau\nÔi thế giới diệu kỳ, chẳng ai chững lại\nĐể khóc cho nỗi buồn tôi\nĐời cười, người chỉ cười với nhau\nÔi thời gian diệu kỳ, lòng người diệu kỳ\nLặng lẽ đổi thay nơi ngày mai\nTôi và em giống như hai người dưng đã lạc nhau\nGiữa những dịu dàng đời\nEm và tôi giống như hai người điên đang cuồng si\nGiữa những dịu dàng đời em\nTôi và em giống như hai người điên đang cuồng si\nGiữa những bộn bề đời\nEm và tôi giống như hai người dưng đã lạc nhau\nGiữa những dịu dàng', 'Tôi và em , Pink Prog , Indie , Nhạc trẻ', 0),
(28, 'Vạn Kiếp Sau', 'RHY', '637afa634b057.mp3', '637afa634b059.jpg', 'Sau cơn mưa còn lại gì\nSau yêu thương còn lại gì\nNgoài nước mắt muộn màng\nChẳng để làm gì\nĐôi lứa chia ly vì đâu\nNắng đã tắt trời nhuộm màu\nMây âm u đọng buồn sầu\nĐành khép hết lòng\nVậy mà gió cứ len vào trong nỗi đau\nChẳng cần phải tìm đâu ra lý do\nĐã hết yêu rồi không ai đắn đo\nDuyên nợ đã tận\nThôi đành thôi ngóng trông ai đã từng\nĐã từng trao nhau thế gian quá muộn màng\nMuộn màng để lại yêu như lúc xưa\nGiữa bao la nghìn trùng mây\nDẫu cho vạn kiếp sau này\nBiết đâu sẽ có một ngày\nThấm thoát đã nhiều mùa tàn\nĐêm qua đêm lòng lại càng nhiều suy tư mơ màng\nKhông lẽ kiếp này ta phải chia tay thật sao\nNắng đã tắt trời nhuộm màu\nMây âm u đọng buồn sầu\nĐành khép hết lòng\nVậy mà gió cứ len vào trong nỗi đau\nChẳng cần phải tìm đâu ra lý do\nĐã hết yêu rồi không ai đắn đo\nDuyên nợ đã tận\nThôi đành thôi ngóng trông ai đã từng\nĐã từng trao nhau thế gian quá muộn màng\nMuộn màng để lại yêu như lúc xưa\nGiữa bao la nghìn trùng mây\nDẫu cho vạn kiếp sau này\nBiết đâu\nChẳng cần phải tìm đâu ra lý do\nĐã hết yêu rồi không ai đắn đo\nDuyên nợ đã tận\nThôi đành thôi ngóng trông ai đã từng như lúc xưa\nChẳng cần phải tìm đâu ra lý do\nĐã hết yêu rồi không ai đắn đo\nDuyên nợ đã tận\nThôi đành thôi ngóng trông ai đã từng\nĐã từng trao nhau thế gian quá muộn màng\nMuộn màng để lại yêu như lúc xưa\nGiữa bao la nghìn trùng mây\nDẫu cho vạn kiếp sau này\nBiết đâu sẽ có một ngày\nGiữa bao la nghìn trùng mây\nDẫu cho vạn kiếp về sau', 'Vạn Kiếp Sau , RHY , Indie , Nhạc trẻ', 0),
(29, 'Về phía mưa', 'Thế Bảo', '637afa9327248.mp3', '637afa932724c.jpg', 'Cũng đã lâu hai ta chẳng bước đi chung trên con phố dài\nCũng đã lâu yêu thương anh mang vứt ra ngoài kia\nGiấu em vào trong từng giây phút bộn bề\nTự mình ngăn dòng ký ức ùa về\nMà khi mưa lại rơi, lòng anh vẫn chơi vơi\nDòng tin cuối đã xem, cũng đã bao lâu không ai ngó ngàng\nTừng con số vẫn quen, dẫu chuyện mình đã lỡ làng\nNgày dặn lòng quên mà đêm vẫn nhớ\nChẳng dám thêm ai dù lòng bơ vơ\nCứ lao thật vội vào mưa chạy vào ký ức xưa\nChạy thật nhanh vào cơn mưa ấy, để anh quên được cảm giác này\nĐể bỏ rơi mùa yêu đã cũ, chạy theo anh đã suốt mấy thu\nVà tập quen rằng em đã có một ai khác trong mưa đứng chờ\nPhố vắng không em thẫn thờ, lối cũ riêng anh bơ vơ\nChạy thật nhanh vào cơn mưa ấy, để không ai nhận ra lúc này\nChỉ giọt mưa hiểu anh ra sao, chỉ mưa biết mình đau thế nào\nĐoạn đường ta còn dang dở đấy, cần bao nhiêu yêu thương lấp đầy\nĐể thấy đêm không còn dài\nĐể thấy tim ta trở lại như ngày xưa\nDòng tin cuối đã xem, cũng đã bao lâu không ai ngó ngàng\nTừng con số vẫn quen, dẫu chuyện mình đã lỡ làng\nNgày dặn lòng quên mà đêm vẫn nhớ\nChẳng dám thêm ai dù lòng bơ vơ\nCứ lao thật vội vào mưa chạy vào ký ức xưa\nChạy thật nhanh vào cơn mưa ấy, để anh quên được cảm giác này\nĐể bỏ rơi mùa yêu đã cũ, chạy theo anh đã suốt mấy thu\nVà tập quen rằng em đã có một ai khác trong mưa đứng chờ\nPhố vắng không em thẫn thờ, lối cũ riêng anh bơ vơ\nChạy thật nhanh vào cơn mưa ấy, để không ai nhận ra lúc này\nChỉ giọt mưa hiểu anh ra sao, chỉ mưa biết mình đau thế nào\nĐoạn đường ta còn dang dở đấy, cần bao nhiêu yêu thương lấp đầy\nĐể thấy đêm không còn dài\nVà để thấy tim ta trở lại như ngày xưa\nTrả lại cho em góc phố quen lẻ loi mưa bay giăng kín lối\nTrả em từng câu yêu thương nụ hôn vương của đêm lạnh giá\nChạy thật nhanh vào cơn mưa ấy, để anh quên được cảm giác này\nĐể bỏ rơi mùa yêu đã cũ, chạy theo anh đã suốt mấy thu\nVà tập quen rằng em đã có một ai khác trong mưa đứng chờ\nPhố vắng không em thẫn thờ, lối cũ riêng anh bơ vơ\nChạy thật nhanh vào cơn mưa ấy, để không ai nhận ra lúc này\nChỉ giọt mưa hiểu anh ra sao, chỉ mưa biết mình đau thế nào\nĐoạn đường ta còn dang dở đấy, cần bao nhiêu yêu thương lấp đầy\nĐể thấy đêm không còn dài\nVà để thấy em đã mãi mãi cách xa\nĐể thấy đêm không còn dài\nĐể thấy tim ta trở lại như ngày xưa', 'Về phía mưa , Thế Bảo , Indie , Nhạc trẻ', 0),
(30, 'Viết về yêu xa', 'Dịp, Đăng Răng To', '637afac607a55.mp3', '637afac607a59.jpg', 'Yêu xa là thứ giết chết đôi ta vì khoảng cách\nTừng ngày từng chiều cuối đông thẫn thờ một mình em\nYêu xa là khi nhớ điên lên mà lại xa\nTừng dòng từng dòng tin nhắn kia quá phớt lờ với em\nĐôi khi trong lòng em thấy biết bao nhiêu là buồn bã\nVì dường ánh mắt kia hết yêu em rồi đúng không\nRap:\nYêu xa là khi mà bất kì lúc nào cũng thấy nhớ\nChẳng gặp được nhau nên để mặt em ở màn hình chờ\nYêu xa là khi mà lòng cứ nơm nớp sợ\nRằng em sẽ có một người nào khác thay vòng tay anh kế bên che chở\nAnh không muốn nghĩ lung tung đôi khi call em bỗng nhiên lúng túng\nNghe nụ cười em nghe tiếng thở anh thấy vui như một thằng khùng\nBiết yêu xa là khổ nhưng nghe giọng nói mỗi trời đêm đen\nDặn lòng như thế là đủ bù cho việc anh chẳng thể bên em\nCăn phòng anh, đêm se lạnh và có chút tàn đang bay\nEm nợ anh một lần gặp anh nợ em một lần đan tay\nSẽ cố để tới vén tóc em mặc kệ đường dài tổn sức\nCố để tới nói yêu em cho anh một lần thổn thức\nĐôi khi trong lòng em thấy biết bao nhiêu là buồn bã\nLòng em quặn thắt đau mỗi khi mưa vào chiều tàn\nUh... no no no no\nTừng ngày từng chiều cuối đông vẫn luôn một mình em\nI feel lonely everytime without u\nBecause youre so far away from me\nOh giờ hai ta ở hai nơi xa\nQua ngàn giông ba nhưng em vẫn ở đây\nĐắm say một người vì một người\n', 'Viết về yêu xa , Dịp , Đăng Răng To, Nhạc trẻ', 0);

-- --------------------------------------------------------

--
-- Table structure for table `verify`
--

CREATE TABLE `verify` (
  `email` varchar(255) NOT NULL,
  `code` varchar(20) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `verify`
--

INSERT INTO `verify` (`email`, `code`) VALUES
('nguyentrungnghiacmp5123@gmail.com', '843670'),
('phuctran12421@gmail.com', '777854');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `accounts`
--
ALTER TABLE `accounts`
  ADD PRIMARY KEY (`email`);

--
-- Indexes for table `play`
--
ALTER TABLE `play`
  ADD PRIMARY KEY (`number`),
  ADD KEY `songs_play` (`id`),
  ADD KEY `accounts_play` (`email`);

--
-- Indexes for table `songs`
--
ALTER TABLE `songs`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `verify`
--
ALTER TABLE `verify`
  ADD UNIQUE KEY `email` (`email`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `play`
--
ALTER TABLE `play`
  MODIFY `number` int(11) NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT for table `songs`
--
ALTER TABLE `songs`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=31;

--
-- Constraints for dumped tables
--

--
-- Constraints for table `play`
--
ALTER TABLE `play`
  ADD CONSTRAINT `accounts_play` FOREIGN KEY (`email`) REFERENCES `accounts` (`email`) ON DELETE CASCADE ON UPDATE CASCADE,
  ADD CONSTRAINT `songs_play` FOREIGN KEY (`id`) REFERENCES `songs` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
